# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_DB: canvas
    ports:
      - 5433:5432
  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_USER: postgres_test
      POSTGRES_DB: canvas_test
    ports:
      - 5434:5432
