// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Canvas struct {
	ID       string       `json:"id"`
	Name     string       `json:"name"`
	Contents []*Rectangle `json:"contents"`
}

type NewCanvas struct {
	Name string `json:"Name"`
}

type NewRectangle struct {
	CanvasID string `json:"canvasId"`
	X        int    `json:"x"`
	Y        int    `json:"y"`
	Width    int    `json:"width"`
	Height   int    `json:"height"`
	Fill     string `json:"fill"`
	Outline  string `json:"outline"`
}

type Rectangle struct {
	ID      string `json:"id"`
	X       int    `json:"x"`
	Y       int    `json:"y"`
	Width   int    `json:"width"`
	Height  int    `json:"height"`
	Fill    string `json:"fill"`
	Outline string `json:"outline"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
